name: 'dbt_extend'
version: '0.2.4'

target-path: "target"
clean-targets: ["target", "dbt_modules"]
macro-paths: ["macros"]
log-path: "logs"

require-dbt-version: ">=0.13.0"
profile: dw
quoting:
    identifier: false
    schema: false

models:
    vars:
        'show_deprecation_warning': false